spring:
  application:
    name: silvioluizbassi

  datasource:
    url: jdbc:mysql://localhost:3306/silviobassi
    username: silvio
    password: mysql123
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

server:
  error:
    include-message: always

springdoc:
  api-docs:
    path: /api-docs

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      probes:
        enabled: true