apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: infnet-app
spec:
  type: ClusterIP
  ports:
    - port: 3306
  selector:
    app: mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deploy
  namespace: infnet-app
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:9.2.0
          name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "root"
            - name: MYSQL_DATABASE
              value: "silviobassi"
            - name: MYSQL_USER
              value: "silvio"
            - name: MYSQL_PASSWORD
              value: "mysql123"
          ports:
            - containerPort: 3306
              name: mysql