apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-course-deploy
spec:
  replicas: 4
  selector:
    matchLabels:
      app: app-course
  template:
    metadata:
      labels:
        app: app-course
    spec:
      containers:
        - name: app-course
          image: silviobassi/app-course:1.4.1  # Substitua pelo nome correto da imagem
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://mysql-svc:3306/silviobassi"
            - name: SPRING_DATASOURCE_USERNAME
              value: "silvio"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "mysql123"
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: "/actuator/health/liveness"
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: "/actuator/health/readiness"
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: app-course-svc
spec:
  selector:
    app: app-course
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
